In [16]:
import pandas as pd
import json
import urllib
import urllib.request

In [17]:
station_dresden = "01048"

In [18]:
first_date = "2019-01-01"

In [19]:
last_date = "2020-12-31"

In [20]:
url = f"https://api.brightsky.dev/weather?date={first_date}&last_date={last_date}&dwd_station_id={station_dresden}"
req = urllib.request.Request(url)
response = urllib.request.urlopen(req)
data = response.read()
values = json.loads(data)

In [21]:
df_new= pd.DataFrame(values['weather'])

In [22]:
df_new

,timestamp,source_id,precipitation,pressure_msl,sunshine,temperature,wind_direction,wind_speed,cloud_cover,dew_point,relative_humidity,visibility,wind_gust_direction,wind_gust_speed,condition,icon,fallback_source_ids
0,2019-01-01T00:00:00+00:00,6937,0.1,1028.50,NaN,7.0,260,19.1,100.0,6.7,98,3800,250.0,31.3,rain,cloudy,NaN
1,2019-01-01T01:00:00+00:00,6937,0.0,1027.80,NaN,7.1,260,19.4,100.0,6.3,95,7000,260.0,31.3,rain,cloudy,NaN
2,2019-01-01T02:00:00+00:00,6937,0.0,1027.09,NaN,7.0,250,16.2,100.0,5.8,92,11000,250.0,29.5,dry,cloudy,NaN
3,2019-01-01T03:00:00+00:00,6937,0.0,1026.00,0.0,7.0,240,20.2,100.0,5.4,90,15000,250.0,31.3,dry,cloudy,NaN
4,2019-01-01T04:00:00+00:00,6937,0.0,1024.70,0.0,7.2,240,21.2,100.0,4.1,81,20000,240.0,35.6,dry,cloudy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17516,2020-12-30T20:00:00+00:00,120052,0.0,1006.30,0.0,3.0,170,12.6,87.0,-1.1,74,50000,160.0,18.4,dry,cloudy,NaN
17517,2020-12-30T21:00:00+00:00,120052,0.0,1006.40,NaN,2.9,170,14.0,75.0,-1.5,73,50000,170.0,18.4,dry,partly-cloudy-night,NaN
17518,2020-12-30T22:00:00+00:00,120052,0.0,1007.00,NaN,1.5,180,14.8,37.0,-2.0,77,50000,180.0,22.7,dry,partly-cloudy-night,NaN
17519,2020-12-30T23:00:00+00:00,120052,0.0,1007.00,NaN,1.8,180,15.5,50.0,-1.7,78,50000,210.0,21.6,dry,partly-cloudy-night,NaN
17520,2020-12-31T00:00:00+00:00,120052,0.0,1007.00,NaN,1.7,200,16.6,50.0,-1.9,77,50000,200.0,25.9,dry,partly-cloudy-night,NaN

In [23]:
df_new.to_pickle("weather_dresden.pkl")